
[ HMisc-ftp://ftp.uni-bayreuth.de/pub/math/statlib/S/Harrell/help/Hmisc/html/sedit.html)

[stringr](https://cran.r-project.org/web/packages/stringr/stringr.pdf)

[Basic String](https://www.r-bloggers.com/basic-text-string-functions-in-r/)

[Pattern matching and Replacement](https://stat.ethz.ch/R-manual/R-devel/library/base/html/grep.html)

[]()

```{r creating a string}
my_string<-"Hello World!!!!"

"Hello World!!!!"%in% my_string
```

Searching for a substring within a string. We employ the function grepl() for this purpose.
```{r substring testing}
grepl('Hello', my_string) #returns TRUE
#But, this command returns false
grepl('hello', my_string)
#How about this?
grepl('hello', my_string, ignore.case = T)
```

[finding location of character pattern in string](https://stackoverflow.com/questions/14249562/find-location-of-character-in-string)
```{r location of substring}
gregexpr('!', my_string)

```

Converting **Strings** to **Numbers**
```{r}
number<-"1234.5"
as.integer(number)
as.character(number)
as.numeric(number)
as.complex(number)

```



### References and further reading:
* [Handling and Processing Strings in R](http://www.gastonsanchez.com/Handling_and_Processing_Strings_in_R.pdf)



